name: Republish

# on:
#  schedule:
#    - cron: '30 17 * * *'  # Run at 5:30 pm UTC every day.

# FIXME: Re-enable CRON
on: push

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $USER_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/alaincaltieri/financialfallacies/pages/builds
          
        # curl --fail --request POST \
        #   --url  https://api.github.com/repos/alaincaltieri/financialfallacies/pages/builds \
        #   --header "Authorization: Bearer $USER_TOKEN"
        
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}